services:
    db:
        image: postgres:15.1
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes: 
            - ./postgres-data:/var/lib/postgresql/data
            # copy the sql script to create tables
            - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
            # copy data
            - ./data:/data
    cron:
        build: ./task_1_2
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}